//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.Mvc;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(PostsSection.CLASS_NAME, typeof(PostsSection))]

namespace CMS.DocumentEngine.Types.Mvc
{
	/// <summary>
	/// Represents a content item of type PostsSection.
	/// </summary>
	public partial class PostsSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "mvc.PostsSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with PostsSection fields.
		/// </summary>
		private readonly PostsSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PostsSectionID.
		/// </summary>
		[DatabaseIDField]
		public int PostsSectionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PostsSectionID"), 0);
			}
			set
			{
				SetValue("PostsSectionID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string PostsSectionName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PostsSectionName"), "");
			}
			set
			{
				SetValue("PostsSectionName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PostsSection fields.
		/// </summary>
		[RegisterProperty]
		public PostsSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PostsSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PostsSectionFields : AbstractHierarchicalObject<PostsSectionFields>
		{
			/// <summary>
			/// The content item of type PostsSection that is a target of the extended API.
			/// </summary>
			private readonly PostsSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PostsSectionFields" /> class with the specified content item of type PostsSection.
			/// </summary>
			/// <param name="instance">The content item of type PostsSection that is a target of the extended API.</param>
			public PostsSectionFields(PostsSection instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PostsSectionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PostsSectionID;
				}
				set
				{
					mInstance.PostsSectionID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.PostsSectionName;
				}
				set
				{
					mInstance.PostsSectionName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PostsSection" /> class.
		/// </summary>
		public PostsSection() : base(CLASS_NAME)
		{
			mFields = new PostsSectionFields(this);
		}

		#endregion
	}
}